name: ci

on: push

jobs:
  ci:
    env:
      PORT: 3000
      SERVER_SECRET: ${{ secrets.SERVER_SECRET}}
      MONGODB_URI: ${{ secrets.MONGODB_URI}}
      PLATFORM_URI: http://localhost:3002
      SERVER_URI: http://localhost:3000
      SERVER_EMAIL: karanikio@auth.gr
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY}}
      USERID: ${{ secrets.USERID}}
      USERNAME: ${{ secrets.USERNAME}}
      USEREMAIL: ${{ secrets.USEREMAIL}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: /actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/giorgos-branch'
    steps:
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/se2/25/se2-backend
            git reset --hard origin/giorgos-branch
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-25 giorgos-branch
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-25'

